add text align on calculator component
budiadiono/react-native-calculator pull request #3
Opened 2018-11-12 16:32 UTC by WesleyFaveri

2018-11-16 23:12 UTC, budiadiono requested changes
This pull request looks good! Just need some small changes and also you need to update the test snapshot by doing `yarn test -u`.

2018-11-16 23:12 UTC, budiadiono commented on src/interface.ts
> +  /**
This comment causing `[tslint] asterisks in jsdoc must be aligned [jsdoc-format]` error raised. Please do :
```
/**
   * Digit align display
   */
```
instead and remove extra line above doc comment.

2018-11-16 23:12 UTC, budiadiono commented on src/interface.ts
> +  displayTextAlign?: string;
Instead of using `string` as type, please use `"auto" | "left" | "right" | "center" | "justify"` instead for type safety.

2018-11-19 10:47 UTC, WesleyFaveri commented
Done, i think

2018-11-19 23:08 UTC, budiadiono commented
Travis still rejects it, I think you need to update the test snapshots by doing `yarn test -u` and commit the snapshots changes.

2018-11-20 22:13 UTC, merged